### PR TITLE
Add support for package managers

### PR DESCRIPTION
**Pull request by douglasjacobsen**
This merge adds functionality to define and control which package manager is used within a given experiment. Relevant schema sections, commands, and unit tests are updated based on this change, and the `known_applications` unit test is updated to sweep over all package managers as well.

### CODE REVIEW

**Comment by linsword13** [comment]
Not sure if it's expected to work right now, but when running the `known_applications` test, I got a bunch of these ModuleNotFoundError:

```
test_known_applications[cloverleaf-spack] - ModuleNotFoundError: No module named 'ramble.pkg_man.builtin.spack_lightweight'
```

**Comment by rfbgo** [comment]
> Not sure if it's expected to work right now, but when running the `known_applications` test, I got a bunch of these ModuleNotFoundError:
> 
> ```
> test_known_applications[cloverleaf-spack] - ModuleNotFoundError: No module named 'ramble.pkg_man.builtin.spack_lightweight'
> ```

I checked on both my OSX laptop and a linux VM and don't see this issue when using the new branch. What env do you see this in? Might be worth seeing if you can repro on a shared VM

**Comment by linsword13** [comment]
> > Not sure if it's expected to work right now, but when running the `known_applications` test, I got a bunch of these ModuleNotFoundError:
> 
> > 
> 
> > ```
> 
> > test_known_applications[cloverleaf-spack] - ModuleNotFoundError: No module named 'ramble.pkg_man.builtin.spack_lightweight'
> 
> > ```
> 
> 
> 
> I checked on both my OSX laptop and a linux VM and don't see this issue when using the new branch. What env do you see this in? Might be worth seeing if you can repro on a shared VM

Yeah this seems related to python version. I see this on 3.12, but it works on 3.10.

**Comment by rfbgo** [comment]
> > > Not sure if it's expected to work right now, but when running the `known_applications` test, I got a bunch of these ModuleNotFoundError:
> > 
> > 
> > > 
> > 
> > 
> > > 
> > 
> > 
> > > test_known_applications[cloverleaf-spack] - ModuleNotFoundError: No module named 'ramble.pkg_man.builtin.spack_lightweight'
> > 
> > 
> > > 
> > 
> > 
> > I checked on both my OSX laptop and a linux VM and don't see this issue when using the new branch. What env do you see this in? Might be worth seeing if you can repro on a shared VM
> 
> Yeah this seems related to python version. I see this on 3.12, but it works on 3.10.

Awesome, thanks. We confirmed it was some issue in the `sys` path magic for python 3.12 and it was also affecting modifiers. Doug just pushed a fix -- great find all

**Comment by linsword13** [comment]
There's one remaining unit-test failure for `test_package_path_variables`. Is that related to the package_path variable change?

**Comment by linsword13** [comment]
With the latest commit, here are the only remaining failed tests:

```
FAILED lib/ramble/ramble/test/end_to_end/known_applications.py::test_known_applications[spack-stack-spack] - AttributeError: 'SpackStack' object has no attribute 'spack_runner'
FAILED lib/ramble/ramble/test/end_to_end/known_applications.py::test_known_applications[spack-stack-spack-lightweight] - AttributeError: 'SpackStack' object has no attribute 'spack_runner'
```

**Review by linsword13 — APPROVED** [review]
